[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiogram==3.3.0",
    "aiohttp>=3.9.5",
    "telegram>=0.0.1",
]
